# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sdm710-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter RMX1901 RMX1921 RMX1971 RMX1851,$(TARGET_DEVICE)),)

endif
